[options]
addons_path = /Users/mrwen/Documents/Github/modryn-odoo/odoo/addons,/Users/mrwen/Documents/Github/modryn-odoo/addons
data_dir = /Users/mrwen/Documents/Github/modryn-odoo/.odoo-data
db_host = 
db_user = mrwen
db_name = modryn_template,bella,noga
dbfilter = ^%d$
list_db = True
http_port = 8069
workers = 0
log_level = info
admin_passwd = $pbkdf2-sha512$600000$VQrBuBfi/B.jdG4txXhvTQ$Um8Jrda1nWvzE38rG3zPteI3tS5QSpow0Y6eoD3dMOd1KcesnsOfW23MXrVDyWAiXR0Lf6ZP4PfGYrRxAZrbLA

