#!/usr/bin/env bash
# Regenerate /etc/nginx/tenants.map from the db_name line in /etc/odoo/odoo.conf.
#
# ONE SOURCE OF TRUTH. nginx must not serve a hostname whose database Odoo's
# cron enumerator has never heard of, and the enumerator must not poll a
# database nginx will never route to. Deriving one from the other makes the two
# incapable of drifting apart; maintaining two lists guarantees they eventually
# do, in whichever direction is least visible.
#
# Called by provision.sh, new_boutique_prod.sh and deploy.sh. Does NOT reload
# nginx — the caller decides when, because a reload in the middle of a
# provisioning run would publish a hostname whose database is half-built.
set -euo pipefail

ODOO_CONF="${ODOO_CONF:-/etc/odoo/odoo.conf}"
MAP_FILE="${MAP_FILE:-/etc/nginx/tenants.map}"
ENV_FILE="${ENV_FILE:-/etc/modryn/deploy.env}"

[ -r "$ODOO_CONF" ] || { echo "!! cannot read $ODOO_CONF" >&2; exit 1; }
# shellcheck disable=SC1090
[ -r "$ENV_FILE" ] && { set -a; . "$ENV_FILE"; set +a; }
[ -n "${DOMAIN:-}" ] || { echo "!! DOMAIN unset (expected in $ENV_FILE)" >&2; exit 1; }

# The FIRST uncommented db_name assignment wins, matching how Odoo's own
# ConfigParser reads the file. Anchoring on '^' skips the `;`-commented
# explanations above it, which do contain the words db_name.
DB_NAME_LINE="$(grep -E '^[[:space:]]*db_name[[:space:]]*=' "$ODOO_CONF" | head -n 1 || true)"
[ -n "$DB_NAME_LINE" ] || { echo "!! no db_name line in $ODOO_CONF" >&2; exit 1; }

DBS="${DB_NAME_LINE#*=}"
DBS="${DBS//[[:space:]]/}"

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "# GENERATED by gen_tenants_map.sh from db_name in $ODOO_CONF."
  echo "# DO NOT HAND-EDIT — the next provisioning run overwrites it."
  echo "# Generated $(date -u +%Y-%m-%dT%H:%M:%SZ)"
} > "$TMP"

COUNT=0
IFS=','
for db in $DBS; do
  [ -n "$db" ] || continue
  # modryn_template is deliberately absent from db_name in production (a held
  # connection blocks `createdb -T`), but guard anyway: it is not a tenant and
  # must never be routable from the internet.
  if [ "$db" = "modryn_template" ]; then
    echo "!! refusing to publish modryn_template as a tenant hostname" >&2
    exit 1
  fi
  printf '%s.%s  1;\n' "$db" "$DOMAIN" >> "$TMP"
  COUNT=$((COUNT + 1))
done
unset IFS

# Zero tenants is legitimate exactly once — on a freshly provisioned box, before
# the first boutique. It is NOT legitimate later, and an empty map means every
# hostname 404s, so say so rather than writing it quietly. The missing-line case
# is a different failure and already exited above.
if [ "$COUNT" -eq 0 ]; then
  echo "!! db_name lists no tenants — writing an empty map (every host will 404)" >&2
fi

install -m 0644 -o root -g root "$TMP" "$MAP_FILE"
echo "wrote $MAP_FILE ($COUNT tenant(s))"
