#!/usr/bin/env python3
"""Fetch the two MODRYN families as self-hosted woff2, and generate their SCSS.

    ./scripts/fetch_fonts.py

RUN ONCE. Both the .woff2 files and the generated .scss are COMMITTED.

This is deliberately not a build step. A build step that reaches the network is
a build step that fails the day Google rate-limits the box — and it would
reintroduce the third-party dependency launch gate 6 exists to remove, merely
moved from the visitor's browser into our deploy.

WHY THIS GENERATES THE SCSS INSTEAD OF LEAVING IT HAND-WRITTEN
Google splits each weight across three unicode-range subsets (hebrew, latin-ext,
latin). Hand-writing six @font-face blocks — one per weight — silently drops two
of the three, and the one most easily dropped is `hebrew`, which carries
U+0590-05FF *and U+20AA, the shekel sign*. A Hebrew storefront printing shekel
prices would fall back to a system font for every character that matters, and
the page would still look approximately right to anyone reviewing in English.
That is precisely the failure this repo keeps finding: a check, or a font, with
no subject. Generating the SCSS from the same CSS the bytes came from makes the
ranges and the files unable to drift.

THE CHROME UA IS LOAD-BEARING. Google serves ttf/eot to any user-agent it does
not recognise, and woff2 is the only format worth shipping.
"""

import hashlib
import pathlib
import re
import subprocess
import sys

UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) "
      "Chrome/101.0.4951.41 Safari/537.36")

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEST = ROOT / "addons/modryn_theme/static/src/fonts"
SCSS = ROOT / "addons/modryn_theme/static/src/scss/fonts.generated.scss"
URL_PREFIX = "/modryn_theme/static/src/fonts"

# The weights are exactly what primary_variables.scss used to ask Google for,
# so this is not a design change.
FAMILIES = [
    ("Assistant", "Assistant:400,600,700", "assistant"),
    ("Frank Ruhl Libre", "Frank+Ruhl+Libre:400,500,700", "frank-ruhl-libre"),
]

BLOCK = re.compile(
    r"/\*\s*(?P<subset>[\w-]+)\s*\*/\s*@font-face\s*\{(?P<body>[^}]*)\}", re.S)


def curl(url: str, binary: bool = False):
    out = subprocess.run(
        ["curl", "-sfA", UA, url], capture_output=True, check=True).stdout
    return out if binary else out.decode()


def main() -> int:
    DEST.mkdir(parents=True, exist_ok=True)
    by_digest: dict[str, str] = {}   # content hash -> filename already written
    faces: list[dict] = []

    for family, spec, slug in FAMILIES:
        css = curl(f"https://fonts.googleapis.com/css?family={spec}"
                   f"&subset=hebrew,latin")
        blocks = list(BLOCK.finditer(css))
        if not blocks:
            print(f"!! no @font-face blocks for {spec} — Google changed the CSS "
                  f"shape; this script must be re-read, not re-run", file=sys.stderr)
            return 1

        for m in blocks:
            body, subset = m.group("body"), m.group("subset")
            weight = re.search(r"font-weight:\s*(\d+)", body)
            url = re.search(r"url\((https://fonts\.gstatic\.com/[^)]+\.woff2)\)", body)
            urange = re.search(r"unicode-range:\s*([^;]+);", body)
            if not (weight and url and urange):
                print(f"!! incomplete @font-face in {spec} ({subset})", file=sys.stderr)
                return 1
            weight, url, urange = weight.group(1), url.group(1), urange.group(1).strip()

            data = curl(url, binary=True)
            digest = hashlib.sha256(data).hexdigest()
            # Google serves ONE variable woff2 for every weight of some families
            # (Assistant is one), so naming purely by weight would commit three
            # byte-identical copies. Deduplicate by content and let the three
            # @font-face blocks point at the same file — which is exactly what
            # Google's own CSS does.
            if digest in by_digest:
                name = by_digest[digest]
            else:
                name = f"{slug}-{subset}-{weight}.woff2"
                (DEST / name).write_bytes(data)
                by_digest[digest] = name
                print(f"  {name:<34} {len(data):>6} bytes")

            faces.append(dict(family=family, weight=weight, name=name,
                              subset=subset, urange=urange))

    header = f"""\
// GENERATED by scripts/fetch_fonts.py — DO NOT EDIT BY HAND.
//
// The six @font-face declarations that replace the two
//   @import url("https://fonts.googleapis.com/css?family=...")
// lines that odoo/addons/website/static/src/scss/website.scss:10 used to compile
// into every frontend bundle. That was never a <link> anyone could see in the
// page source — it was a CSS @import inside a ~995 KB stylesheet, which is why
// it survived review as long as it did.
//
// {len(faces)} faces over {len(by_digest)} files: Google splits each weight across three
// unicode-range subsets, and serves ONE variable file for every weight of some
// families, so several faces deliberately point at the same bytes.
//
// THE `hebrew` SUBSET IS THE LOAD-BEARING ONE. It carries U+0590-05FF and
// U+20AA — Hebrew, and the shekel sign the storefront prints on every price.
// Shipping latin only would render the whole catalogue in a fallback face and
// still look correct to anyone reviewing in English.
//
// Absolute /modryn_theme/... paths, not relative: Odoo rewrites relative url()
// against the SCSS file's own directory. An absolute path says what it means
// and survives the file moving.
//
// font-display: swap keeps Hebrew text visible during the fetch — the same
// behaviour the Google URL asked for with &display=swap, so this is not a
// rendering change.
//
// NOT HERE, DELIBERATELY: an Arabic face. Neither family has Arabic glyphs, and
// Odoo's 'Odoo Unicode Support Noto' fallback has no @font-face in any frontend
// bundle. /ar/shop renders in the OS default sans-serif today and still will.
// Adding an Arabic face is a design decision, not part of removing a third party.
//
// Both families are SIL OFL 1.1 — see fonts/OFL.txt.
"""

    parts = [header]
    for f in faces:
        parts.append(f"""
/* {f['subset']} */
@font-face {{
    font-family: '{f['family']}';
    font-style: normal;
    font-weight: {f['weight']};
    font-display: swap;
    src: url('{URL_PREFIX}/{f['name']}') format('woff2');
    unicode-range: {f['urange']};
}}""")
    SCSS.write_text("".join(parts) + "\n")

    (DEST / "OFL.txt").write_text("""\
Assistant and Frank Ruhl Libre are licensed under the SIL Open Font License 1.1.

  https://openfontlicense.org/open-font-license-official-text/

The OFL permits self-hosting and redistribution and requires no attribution in
the user interface. The .woff2 files beside this notice are Google Fonts' own
hebrew+latin subsets, fetched once by scripts/fetch_fonts.py and committed so
that neither a build nor a page load depends on a third party.
""")

    print(f"\n{len(faces)} faces over {len(by_digest)} files -> "
          f"{SCSS.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
