from . import audit_log
from . import calendar_event
from . import hr_employee
from . import res_partner
from . import sale
from . import task
from . import dress_type
from . import dress
from . import dress_stock
from . import discount_code
